### ISSUE TITLE
url https://test.pypi.org/simple/ siamese-rit-change

### ISSUE THREAD

**Issue by zhangyuxin0** [vbhavank/Siamese-neural-network-for-change-detection#6]
why this url not found

**Comment by vbhavank** [comment]
@zhangyuxin0 I had to take it down due to different versions of the code that was underneath the package and have not been able to re-packaging due to time issues. I apologize for the inconvenience.

我不得不将其删除，因为包装下面的代码版本不同，并且由于时间问题而无法重新打包。我带来的不便表示歉意
