### ISSUE TITLE
Ground truth

### ISSUE THREAD

**Issue by ormosia6** [vbhavank/Siamese-neural-network-for-change-detection#7]
Is it means I need to rename the images in my dateset?like AChip1 and ANeg1,and then copy the filename of AChip1 into input1.txt,while copy ANeg1 into input2.txt?But where should I put the Ground Truth of this pair?

**Comment by ormosia6** [comment]
where can i find the corresponding paper about the code?

**Comment by vbhavank** [comment]
@ormosia6  You only need one input.txt for training. Either input1.txt or input2.txt

You do not have to rename them to AChip** or ANeg**. Just have them in a text file as follows:
/path/to/first/patch2,/path/to/second/patch1, N  
/path/to/first/patch2,/path/to/second/patch2, C  
........

You need to assign a label on the go (either a 'N' or 'C') . Where N is a no-change and C is change. The N or C are present at the end of each file.
If N is translated to label '1' during training or testing, then C=~N=~1=0. 

If you decide to not go through this indirect reference, you can simply assign them as 0 or 1.

The paper for the code is at https://www.researchgate.net/publication/331059954_SIAMESE_NETWORK_WITH_MULTI-LEVEL_FEATURES_FOR_PATCH-BASED_CHANGE_DETECTION_IN_SATELLITE_IMAGERY

**Comment by ormosia6** [comment]
Thank you very much for your patient reply!!!
